### ISSUE TITLE
Note.

### ISSUE THREAD

**Issue by Ke-i-ko** [AplhaSlayer1964/kemono-dl#1]
Worth noting that there are some spelling errors, not entirely sure whether or not that is intentional with Download_Location (Downalod_Loaction) string. In addition, do you have any plans to add support for the other services? Such as Fantia, Pixiv Fanbox and so on?

**Comment by AplhaSlayer1964** [comment]
Ya spelling mistakes are not intentional lol. I wrote the first version really fast at like 4am. Right now this is probably only going to work with kemono party. Those other sights I believe you need to pay to get access to content so testing wouldn't be possible.

**Comment by AplhaSlayer1964** [comment]
Ok so I didn't realize that kemono.party also logged those services as I only used it for parteon posts before. I will look into adding full support for the others (mainly separation in folder creation). In the mean time it should still work for the others as the site seems to use the same layout.
