### ISSUE TITLE
Post is marked as downloaded in the archive file even though it has not been downloaded.

### ISSUE THREAD

**Issue by neuromememachine** [AplhaSlayer1964/kemono-dl#13]
version: kemono-dl 2021.10.21
my command: python kemono-dl.py -i --cookies "cookies.txt" --favorite-users -a archive.txt

As the title says, when the download of a post starts, the ID of the post is written to the archive file.
Even if a post contains multiple attachments (e.g. multiple images) and the download of some of them fails, it will not be downloaded again the next time the program is run because it is already written in the archive file.
Wouldn't it be better to include them in the archive file when the post download is complete?

(By the way, thank you for adding the ability to download favorite users in bulk. It was very helpful.)

**Comment by AplhaSlayer1964** [comment]
The post id is only written to the archive file when the post completes with no errors. There was a problem that a file might not give an error if the download froze in the middle but that has also just been fixed and doesn't seem to be like what you're describing,

**Comment by AplhaSlayer1964** [comment]
If you look [here](https://github.com/AplhaSlayer1964/kemono-dl/blob/e176890d143b7166767d23426c6628c0dd38a9b1/kemono-dl.py#L262) in the code for kemono-dl.py you can see that the post is only archived if no errors and at the end of the save_post function

**Comment by neuromememachine** [comment]
Okay, this seems to be a bug that occurs when there is already an archive file.

`python kemono-dl.py -i --cookies "cookies.txt" --links SOME_POST -a new_archive.txt
`
As you said, this command did not create the archive file until the download was finished.

If you add the option -archive FILE, it will skip downloading the posts that match the Post ID in the archive file, download the posts that have not been downloaded yet, and add the posts that have been downloaded to the archive file. I thought it would work like this, but in fact, when I look at the archive file at the start of the download, the Post ID that is currently being downloaded is written in the bottom line.

**Comment by AplhaSlayer1964** [comment]
I think you might be miss understanding what's printed to the screen. When it says 
```
Completed downloading post: TITLE
service: [SERIVCE] user_id: [USER_ID] post_id: [POST_ID]
----------------------------------------------------------------------------------------------------
```
The part after `Completed downloading post: TITLE` is that posts info not the next posts info.
