### ISSUE TITLE
(not solved)An issue where the post did not finish downloading but not marked as failed

### ISSUE THREAD

**Issue by mgmcmk** [AplhaSlayer1964/kemono-dl#15]
![image](https://user-images.githubusercontent.com/8914838/138567798-79593700-72a8-4dea-908e-4dbf2357f7df.png)

service: fanbox
user_id: 49906039
post_id: 2245817
I have confirmed that the problem still occurs after the update.
The issue was found in multiple posts.
(The timestamp was added by me to check the log)
Also, there is a problem with the progress bar not showing when downloading the pdf file.

**Comment by AplhaSlayer1964** [comment]
Logging every file should be possible but I also see many complications with doing this. At the very least it would require the program to try to re download the file again and compare them. I also just realized that I need the script to delete the file if it fails so partial files aren't just sitting there.

**Comment by AplhaSlayer1964** [comment]
Apparently the base URL has the sha-256 hash of the file as the file name but the problem is I noticed with some testing that some of the hashes that they have as file names seem to be wrong. I'm asking on their forum about it. If that issue can be figured out then that will be an easy way of checking if a file was already downloaded and if it was downloaded correctly.

**Comment by albertobalsalm** [comment]
Ok. I've been downloading a creator, and when the download fails, it will retry the last file it attempted to download. But if the download stops completely and I have to restart, it will re-download the whole post again. But this works for me.  Thanks a lot for your continuous effort!

**Comment by AplhaSlayer1964** [comment]
So I'm working on using the sha-256 hash in the file name to stop duplicate downloads but I have noticed some of their hashes are wrong (1/10,000 maybe) I have my script being tested with 25 accounts and have only noticed like 3 files that had incorrect hashes.
