### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by NovaResonance** [AplhaSlayer1964/kemono-dl#2]
Specific SubscribeStar would not download without this error, I thought at first maybe SubscribeStar specifically didn't work but I tried both a Patreon and another SubscribeStar and both were successful. 
~My guess is the brackets used in the name of the first file.~ (Nevermind, just noticed files with brackets that worked, I don't know much about this stuff other than getting it to work on my end) 
The artist was Somescrub, this was during an artist download, not a specific post download. 
Great work so far, by the way. Was wondering when someone would be the first to make one for Kemono. 

> D:\Downloaders\Kemono Downloader>python kemono-dl.py --cookies "cookie.txt"
Traceback (most recent call last):
  File "kemono-dl.py", line 233, in <module>
    Download_Post(post, username, service)
  File "kemono-dl.py", line 111, in Download_Post
    os.makedirs(folder_path)
  File "C:\Users\Natalie\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Downloaders\\Kemono Downloader\\Downloads\\subscribestar\\Somescrub \\[2021-02-21 175100] The Little Mermaid'

**Comment by AplhaSlayer1964** [comment]
Quick look and figured out that for some reason the username had a weird space at the end of it. Made it so when the username is got it strips trailing whitespaces. Will push a new release with the fix right away!
