### ISSUE TITLE
output jpeg/jpg files as JPE

### ISSUE THREAD

**Issue by baraa272** [AplhaSlayer1964/kemono-dl#22]
tried to download a whole artist chifuri45 from kemono but I face a strange problems it saves jpg/jpeg files as JPE ??
any solution ??
![Screenshot (7114)](https://user-images.githubusercontent.com/32843097/140984030-5c208076-e7c8-469d-8097-2c8b01bd0730.png)
as you can see png is saved correctly but jpg is saved as jpe

**Comment by AplhaSlayer1964** [comment]
jpe is just another type of jpg/jpeg image format used for web graphics, and if it was downloaded that way that means that's how it was originally uploaded by the user.
