### ISSUE TITLE
403 For any /user

### ISSUE THREAD

**Issue by Rozzemak** [AplhaSlayer1964/kemono-dl#23]
Just try to download something. Am I the only one ? 
Im not banned. Site works for me.
I even created new acc and used VPN, but still no luck.

**Comment by AplhaSlayer1964** [comment]
That seems like an network issue on your end. Script works normally for me. Do you have a proper cookies file?

**Comment by Rozzemak** [comment]
Firefox cookie addon export issue. (developer edition only maybe?)
I tried to export cookie with chrome and it just worked.

**Comment by AplhaSlayer1964** [comment]
Interesting. I have only tested the firefox extension a couple times as it's not my primary browser. I will look into it.
