### ISSUE TITLE
403 Client Error: Forbidden for url: https://data3.kemono.party/data/bf

### ISSUE THREAD

**Issue by amirullahizzan** [AplhaSlayer1964/kemono-dl#26]
[Downloading]: 046_elf_01.png
[Error] downloading: https://kemono.party/data/bf/71/bf7126266425524e514f41ab8afb5bc6f174559205c36b59b97435534e0b5267.png
403 Client Error: Forbidden for url: https://data3.kemono.party/data/bf/71/bf7126266425524e514f41ab8afb5bc6f174559205c36b59b97435534e0b5267.png
[info] Retrying download in 30 seconds. (1/3)

I got this error what should I do?

**Comment by AplhaSlayer1964** [comment]
The 403 means you got rate limited you must have downloaded a lot of images in a very short time. Just re run the script. If that still doesn't work please provide the command you used.

**Comment by amirullahizzan** [comment]
I was just downloading like 12 images in a post.

heres the command 

python kemono-dl.py --cookies "cookies.txt" --links https://kemono.party/fanbox/user/18937/post/2435857

I tried downloading it from the user/USERID but it's the same error. I ran my cmd with admin mode also doesnt solve the problem.

**Comment by AplhaSlayer1964** [comment]
I would retry getting your cookie file because all posts downloaded for me.

**Comment by GithubGuest99** [comment]
@amirullahizzan which browser are you using?

**Comment by AplhaSlayer1964** [comment]
Oh ya I hadn't double checked getting the cookies from firefox after someone mentioned a problem in the past.

**Comment by AplhaSlayer1964** [comment]
I will assume this was fixed by getting a new cookie file.  403 errors should only occur when you are blocked by the sites DDOS guard a correct cookie file from the site should get you around that every time.
