### ISSUE TITLE
Cannot open Kemono-dl.py

### ISSUE THREAD

**Issue by Waffledog00** [AplhaSlayer1964/kemono-dl#36]
### Version
 
**Version: C:\Users\123>python kemono-dl.py --version
python: can't open file 'C:\Users\123\kemono-dl.py': [Errno 2] No such file or directory**

### Service, User ID, Post ID **I can't even open it**

- Service: 
- User ID: 
- Post ID: 

### Your Command
```bash
Please paste the command you used here. 
```
**Any one of the commands that has Kemono-dl.py in it**
### Description of bug

**I followed the tutorial text but I got stuck on "4 and 5"**
### How To Reproduce

I legit don't know
### Error messages and tracebacks

```python
Please paste tracebacks here.
``` **Version: C:\Users\123>python kemono-dl.py --version
python: can't open file 'C:\Users\123\kemono-dl.py': [Errno 2] No such file or directory**

### Additional comments
<!-- Anything else you think might help. -->
I just need to fix this cuz this really ain't working. Please be a bit more clear with your tutorial cuz I might just be dumb but I can't follow the tutorial even a bit without having to fix like 3 bugs.

**Comment by AplhaSlayer1964** [comment]
Are you running the command in the folder where the .py file is?

**Comment by Waffledog00** [comment]
Sorry I'm quite new to Python. How do I do that. I might be doing it but I don't know how to find out.

**Comment by AplhaSlayer1964** [comment]
So you want to open your command prompt in that folder location. Then run the command.

**Comment by Waffledog00** [comment]
Alright thanks. It works now.
