### ISSUE TITLE
I can't download more then 19 files

### ISSUE THREAD

**Issue by Waffledog00** [AplhaSlayer1964/kemono-dl#37]
### Version

Version: Python 3.9.9, 2021.12.07

### Service, User ID, Post ID

- Service: Patreon
- User ID: 17422605
- Post ID: 

### Your Command
```bash
Please paste the command you used here. 
```
python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605
### Description of bug

It downloads about 19 of the files but it suddenly stops and gives this error: 404 Client Error: Not Found for url:
### How To Reproduce

I don't really know but I did "python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605" and it suddenly stopped downloading after around 19 files

### Error messages and tracebacks

```python 
Please paste tracebacks here.
``` 
404 Client Error: Not Found for url:
### Additional comments

No, I do not.

**Comment by AplhaSlayer1964** [comment]
Ya please use '-i' to ignore errors. I will be releasing a new version soon where I changed some things around such as what errors cause the program to crash or not.

**Comment by Waffledog00** [comment]
It gives me this error:
"'-i' is not recognized as an internal or external command,
operable program or batch file."
