### ISSUE TITLE
You closed my last one down

### ISSUE THREAD

**Issue by Waffledog00** [AplhaSlayer1964/kemono-dl#38]
Version
Version: Python 3.9.9, 2021.12.07

Service, User ID, Post ID
Service: Patreon
User ID: 17422605
Post ID:
Your Command
Please paste the command you used here. 
python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605

Description of bug
It downloads about 19 of the files but it suddenly stops and gives this error: 404 Client Error: Not Found for url:

How To Reproduce
I don't really know but I did "python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605" and it suddenly stopped downloading after around 19 files

Error messages and tracebacks
Please paste tracebacks here.
404 Client Error: Not Found for url:

Additional comments
It gives me this error:
"'-i' is not recognized as an internal or external command,
operable program or batch file."

**Comment by AplhaSlayer1964** [comment]
You use it like --cookies, -i

**Comment by Waffledog00** [comment]
Still doesn't work: D:\kemono-dl-2021.12.07>python -m kemono-dl.py --cookies -i
usage: -m [-h] [--version] --cookies COOKIES [-l LINKS] [-f FILE] [--favorite-users] [--favorite-posts] [-o PATH]
          [-a FILE] [-u] [-i] [--yt-dlp] [--post-timeout SEC] [--retry-download COUNT] [--date DATE]
          [--datebefore DATE] [--dateafter DATE] [--min-filesize SIZE] [--max-filesize SIZE] [--only-filetypes EXT]
          [--skip-filetypes EXT] [--skip-content] [--skip-embeds] [--skip-pfp-banner] [--skip-comments]
          [--skip-postfile] [--skip-attachments] [--skip-json] [--force-external] [--force-indexing] [--force-inline]
          [--force-yt-dlp]
-m: error: argument --cookies: expected one argument

**Comment by AplhaSlayer1964** [comment]
You did not seem to pass a cookie file or any links.
