### ISSUE TITLE
Yet again. You closed my last one down.

### ISSUE THREAD

**Issue by Waffledog00** [AplhaSlayer1964/kemono-dl#39]
Version
Version: Python 3.9.9, 2021.12.07

Service, User ID, Post ID
Service: Patreon
User ID: 17422605
Post ID:
Your Command
Please paste the command you used here.
python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605

Description of bug
It downloads about 19 of the files but it suddenly stops and gives this error: 404 Client Error: Not Found for url:

How To Reproduce
I don't really know but I did "python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605" and it suddenly stopped downloading after around 19 files

Error messages and tracebacks
Please paste tracebacks here.
404 Client Error: Not Found for url:

Additional comments `I know this is getting old`
It gives me this error: 
D:\kemono-dl-2021.12.07>python -m kemono-dl.py --cookies -i usage: -m [-h] [--version] --cookies COOKIES [-l LINKS] [-f FILE] [--favorite-users] [--favorite-posts] [-o PATH] [-a FILE] [-u] [-i] [--yt-dlp] [--post-timeout SEC] [--retry-download COUNT] [--date DATE] [--datebefore DATE] [--dateafter DATE] [--min-filesize SIZE] [--max-filesize SIZE] [--only-filetypes EXT] [--skip-filetypes EXT] [--skip-content] [--skip-embeds] [--skip-pfp-banner] [--skip-comments] [--skip-postfile] [--skip-attachments] [--skip-json] [--force-external] [--force-indexing] [--force-inline] [--force-yt-dlp] -m: error: argument --cookies: expected one argument

**Comment by AplhaSlayer1964** [comment]
So just because a bug report is closed doesn't mean you need to re open one you can still comment in it. I closed the report because it wasn't a bug. Not to be rude but please google how to pass parameters to a python program. The command you want is `python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/17422605 -i`

**Comment by AplhaSlayer1964** [comment]
Also I commented on your last issue but it doesn't seem like you passed a cookie file or any links in the last command you put, the one with the errors.

**Comment by AplhaSlayer1964** [comment]
For context why this shouldn't count as a bug is because it is the site giving you a 404 file not found I'd recommend reporting any 404d links to them.

**Comment by ferryfw** [comment]
You can also try --ignore-errors

**Comment by AplhaSlayer1964** [comment]
> You can also try --ignore-errors

Yes --ignore-errors and -i function the same.
