### ISSUE TITLE
Blacklist or whitelist

### ISSUE THREAD

**Issue by snowpelt** [AplhaSlayer1964/kemono-dl#40]
I want to use the --favorite-users option, but I don't want to download the gallery of all my favorite users.

Also, when I use the --favorite-users option, all posts of all users are crawling, but can I specify a range to crawling?
 --date and --archive FILE can prevent duplicate downloads, but it takes a huge amount of time to crawling if there are 100 favorite users.
It would be nice to be able to specify the range of crawling by the Updated date on the Favorite Artists page.

**Comment by AplhaSlayer1964** [comment]
Could you give a better example of what range yo are looking to download of your favorites? Like do you just want the n most recent favorites?

**Comment by snowpelt** [comment]
Yes.
I would like an option to crawling only the n most recent favorites.
Or an option to only crawling favorite users that have been updated within the last n days.

Personally, I think the latter is more convenient. The reason is that the number of galleries updated in a week is not constant.

--

I would also like to have the option to download only certain users.
I have favorite users that I want to download and save, and favorite users that I just want to see on the web.
It would be nice to be able to use Blacklist.txt or whitelist.txt to decide whether or not to allow downloads.

**Comment by AplhaSlayer1964** [comment]
You know you can just pass the links for specific users or put them in a text file and pass that in.

**Comment by snowpelt** [comment]
_"You know you can just pass the links for specific users or put them in a text file and pass that in."_

Please tell me how to do it in detail.
I want to use the --favorite-users option and download only the specific 50 out of the 100 people who have registered as my favorites.

_"Also in the future please use the feature request template."_
I'm sorry. I'll rewrite it again. My requests are these two.


**Option to download only specific users**
I want to use the --favorite-users option and download only the specific 50 out of the 100 people who have registered as my favorites. I have favorite users that I want to download and save, and favorite users that I just want to see on the web.


**Option to only crawling favorite users that have been updated within the last n days.**
Use the --favorite-users option, all posts of all users are crawling.
--date and --archive FILE can prevent duplicate downloads, but it takes a huge amount of time to crawling if there are 100 favorite users.

**Comment by AplhaSlayer1964** [comment]
> Please tell me how to do it in detail. I want to use the --favorite-users option and download only the specific 50 out of the 100 people who have registered as my favorites.

Just use `--links "URL1,URL2,URL3"` or use `--fromfile links.txt` where links.txt has all the profile links of the specific users you want to save. Please read the README all the options are listed.

> I'm sorry. I'll rewrite it again. My requests are these two.

Just please use the given template that is prompted when filing an issue next time.

> **Option to download only specific users** I want to use the --favorite-users option and download only the specific 50 out of the 100 people who have registered as my favorites. I have favorite users that I want to download and save, and favorite users that I just want to see on the web.

I will probably not add a blacklist/ whitelist for favorite users. Please just use `--links` or `--fromfile` if you wish to download specific users.

> **Option to only crawling favorite users that have been updated within the last n days.** Use the --favorite-users option, all posts of all users are crawling. --date and --archive FILE can prevent duplicate downloads, but it takes a huge amount of time to crawling if there are 100 favorite users.

I will consider adding this option.

**Comment by snowpelt** [comment]
Thank you very much.
