### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by GyaruFan** [AplhaSlayer1964/kemono-dl#41]
I downloaded python and typed pip install -r requirements.txt but I got an invalid syntax error. Why? I use python 3.1

**Comment by GyaruFan** [comment]
3.9 also same issue

**Comment by GyaruFan** [comment]
pip install -r F:\Downloader\requirements.txt tried this and also didnt work.

**Comment by AplhaSlayer1964** [comment]
> I downloaded python and typed pip install -r requirements.txt but I got an invalid syntax error. Why? I use python 3.1

So what was the invalid syntax error you get?

**Comment by AplhaSlayer1964** [comment]
Try adding python -m, python3 -m, or py -m to the front. If that doesn't fix it you will need to do some googling as I won't have an answer.
