### ISSUE TITLE
Failed to get the date

### ISSUE THREAD

**Issue by cube-Sugar** [AplhaSlayer1964/kemono-dl#42]
### Version

Version: 2021.12.29

### Your Command
```bash
python3 kemono-dl.py --cookies "cookies.txt" --kemono-favorite-users
```

### Description of bug

- When the option `--kemono-favorite-users` is given, the following error message is displayed, probably because it fails to retrieve the date.
- This error does not occur in version 2021.12.22.　

```bash
python3 kemono-dl.py --cookies "cookies.txt" --kemono-favorite-users
INFO: Gathering favorite users
Traceback (most recent call last):
  File "kemono-dl.py", line 4, in <module>
    main()
  File "/home/XXXXXXXX/kemono-dl-2021.12.29/src/main.py", line 592, in main
    D.add_favorite_artists('kemono')
  File "/home/XXXXXXXX/kemono-dl-2021.12.29/src/main.py", line 70, in add_favorite_artists
    if self._is_update_newer(favorite['updated'], last):
  File "/home/XXXXXXXX/kemono-dl-2021.12.29/src/main.py", line 236, in _is_update_newer
    last_dt = datetime.datetime.strptime(last, r'%a, %d %b %Y %H:%M:%S %Z')
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 01 Jan 1 00:00:00 ' does not match format '%a, %d %b %Y %H:%M:%S %Z'
```

### How To Reproduce

- Run the command with the `--kemono-favorite-users` option. (Version: 2021.12.29)
Example: `python3 kemono-dl.py --cookies "cookies.txt" --kemono-favorite-users`.

This is a translation done by a machine.
I'm sorry if any of this is hard to understand.
Thank you in advance.

**Comment by AplhaSlayer1964** [comment]
Sorry about that I guess I only tested adding the `--favorite-users-updated-within` and not when it is not passed. I just pushed the latest release [here](https://github.com/AplhaSlayer1964/kemono-dl/releases/tag/2021.12.29.01).
