### ISSUE TITLE
Issue with --links command

### ISSUE THREAD

**Issue by sybarix** [AplhaSlayer1964/kemono-dl#44]
### Version

Version: 2021.12.30.01

### Site, Service, User ID, Post ID

- Site: kemono/coomer.party
- Service: NA
- User ID: NA
- Post ID: NA

### Your Command

```bash

@echo off
py kemono-dl.py --cookies "kemono.txt,coomer.txt" --links https://kemono.party/SERVICE/user/USERID,https://coomer.party/SERVICE/user/USERID --output "D:\Storage\Offline\Images\Archivers\KemonoDL" --skip-filetypes "PSD" --ignore-errors --retry-download 1 --kemono-favorite-users --coomer-favorite-users --extract-links --verbose
pause

```

### Description of bug

Using the --links command as per the main post (--links https://kemono.party/SERVICE/user/USERID) results in an error, but the downloads proceed as per normal.

### How To Reproduce

Use the --links command. I've tried the following, with the same results:
--links https://kemono.party/SERVICE/user/USERID
--links https://coomer.party/SERVICE/user/USERID
--links https://kemono.party/SERVICE/user/USERID,https://coomer.party/SERVICE/user/USERID

### Error messages and tracebacks

```python

CRITICAL: No username found: user_id: USERID service: SERVICE

```
[debug.log](https://github.com/AplhaSlayer1964/kemono-dl/files/7795217/debug.log)

**Comment by AplhaSlayer1964** [comment]
That is just a filler link. You have to get the user or post link yourself. You also don't have to pass `--links` if you are using `--kemono-favorite-users`.

**Comment by sybarix** [comment]
I see, thanks. I was confused because the previous versions didn't show the error message, but if the command was redundant in the first place then all's good.
