### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by SaN906** [AplhaSlayer1964/kemono-dl#46]
### Version
[debug.log](https://github.com/AplhaSlayer1964/kemono-dl/files/7819717/debug.log)

Version:2022.01.05

### Site, Service, User ID, Post ID

- Site: kemono.party
- Service: patreon
- User ID: 2339790
- Post ID: 

### Your Command

python kemono-dl.py --cookies "cookies.txt" --links https://kemono.party/patreon/user/2339790

Please replace with command used.
```
python kemono-dl.py --cookies "cookies.txt" --links https://kemono.party/patreon/user/2339790
```

### Description of bug
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SaN\\Desktop\\kemono-dl-2022.01.05\\kemono-dl-2022.01.05\\Downloads\\patreon\\IanHubert [2339790]\\[20220101] [60609262] Everything Nathan Knows About Color Pt 1 - Transfer Functions\\[1]_https___www.patreon.com_media-u_Z0FBQUFBQmgxWlR0X3ZiaUdNWFpRUUY1UEVNMUtQN0VrME1YdUt4c25RYWdmUW5kaHRfWE1kV3JNcTVCUHQzZXRKRUR3SUZCY1g2QmVESHduOXk0UEZ0Z0FQSkwyWmUzQU9MckFkWW9MWGxJdVlRa21iVG5QM05UNzBCMGdBd2wwaG1qbFkxLVl4ZmNRS3g4Q21CUXA5dVZnamR5SGV2OHpnPT0'

### How To Reproduce
python kemono-dl.py --cookies "cookies.txt" --links https://kemono.party/patreon/user/2339790

### Error messages and tracebacks

```python

INFO: Downloading [1]_https___www.patreon.com_media-u_Z0FBQUFBQmgxWlR0X3ZiaUdNWFpRUUY1UEVNMUtQN0VrME1YdUt4c25RYWdmUW5kaHRfWE1kV3JNcTVCUHQzZXRKRUR3SUZCY1g2QmVESHduOXk0UEZ0Z0FQSkwyWmUzQU9MckFkWW9MWGxJdVlRa21iVG5QM05UNzBCMGdBd2wwaG1qbFkxLVl4ZmNRS3g4Q21CUXA5dVZnamR5SGV2OHpnPT0
Traceback (most recent call last):
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\kemono-dl.py", line 4, in <module>
    main()
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 686, in main
    downloader(urls)
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 61, in __init__
    self.add_links()
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 113, in add_links
    self._parse_links(url)
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 121, in _parse_links
    self._find_posts(user.group(1),user.group(2),user.group(3))
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 171, in _find_posts
    self.download_post()
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 183, in download_post
    self._download_attachments()
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 310, in _download_attachments
    self._requests_download(file_url, file_name, file_hash)
  File "C:\Users\SaN\Desktop\kemono-dl-2022.01.05\kemono-dl-2022.01.05\src\main.py", line 496, in _requests_download
    with open(file_name, 'ab') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SaN\\Desktop\\kemono-dl-2022.01.05\\kemono-dl-2022.01.05\\Downloads\\patreon\\IanHubert [2339790]\\[20220101] [60609262] Everything Nathan Knows About Color Pt 1 - Transfer Functions\\[1]_https___www.patreon.com_media-u_Z0FBQUFBQmgxWlR0X3ZiaUdNWFpRUUY1UEVNMUtQN0VrME1YdUt4c25RYWdmUW5kaHRfWE1kV3JNcTVCUHQzZXRKRUR3SUZCY1g2QmVESHduOXk0UEZ0Z0FQSkwyWmUzQU9MckFkWW9MWGxJdVlRa21iVG5QM05UNzBCMGdBd2wwaG1qbFkxLVl4ZmNRS3g4Q21CUXA5dVZnamR5SGV2OHpnPT0'

```

**Comment by AplhaSlayer1964** [comment]
When you installed python did you do the check box to disable path length limit? I just tried with the post with that particular file and it downloaded fine.

**Comment by SaN906** [comment]
i didnt disabled path length limit. i'll try disableing it thanks.

**Comment by AplhaSlayer1964** [comment]
Also looking at that file I got a question for kemono.party WTF is that file name? That should be a jpg but since they gave it that file name it downloads with no extension regardless of right clicking and saving or using the downloader. I would post something about it on their partychan chat thing.

**Comment by SaN906** [comment]
btw i disabled path length limit and i guess its downloading and working now

**Comment by AplhaSlayer1964** [comment]
glad that got it working!

**Comment by SaN906** [comment]
yeah btw thank you so much bro.
