### ISSUE TITLE
.jpe file extensions issue

### ISSUE THREAD

**Issue by AlphaAnother** [AplhaSlayer1964/kemono-dl#47]
### Description

some post will download .jpe images, some old viewer such as perfect viewer can't identify them. so i rename them to .jpeg but downloader will download them again.

### Service, User ID, Post ID

- Site:
- Service:
- User ID:
- Post ID:

### Additional comments

could you change the detection logic of downloaded files to not detect file extensions during file name detection, and let them enter the next hash detection.

**Comment by AplhaSlayer1964** [comment]
So the file extension check is used for the flags `--only-filetypes` and `--skip-filetypes` This check should be done first to stop from having to search for a file and possibly having to compute its hash when it will be skipped anyways. 

I think the problem you are encountering though is that when you change the file name `image.jpe` to `image.jpeg` when it goes to check the hash it can no longer find `image.jpe` so it redownloads the image. I don't know much about `.jpe` file types but if they are interchangeable with `'.jpeg` I could add an option flag to change it before it is downloaded.

**Comment by AplhaSlayer1964** [comment]
If you modify main.py and insert this code between 421 and 422 it will change all `.jpe` file to `.jpeg`. I might add this as an option but it's more of the file viewing software's fault for it not being able to read it.
```python
if os.path.split(file_name)[1].split('.')[-1] == 'jpe':
    file_name = file_name[:-3] + 'jpeg'
```
Lines 421 to 424 should look like this after
```python
    def _requests_download(self, url:str, file_name:str, file_hash:str = None, retry:int = args['retry_download']):
        if os.path.split(file_name)[1].split('.')[-1] == 'jpe':
            file_name = file_name[:-3] + 'jpeg'
        logger.debug(f"Preparing download: File Name: {os.path.split(file_name)[1]} URL: {url}")
```
