### ISSUE TITLE
Don't grab the cookies

### ISSUE THREAD

**Issue by Nerodacles** [AplhaSlayer1964/kemono-dl#49]
### Version
Version: 2022.01.11

### Your Command
```bash
python kemono-dl.py --retry-download 1 --cookies "cookie-kemono.txt,cookie-coomer.txt" -o whatever\raw --archive whatever\archive.txt --kemono-favorite-users --coomer-favorite-users --dateafter 20210101 --save-banner --save-icon --max-filesize 600MB --restrict-names --verbose

```

### Description of bug
The downloader dont want to use the cookies provided.

### How To Reproduce
Just try to download something.

### Error messages and tracebacks
```python

INFO: Gathering favorite users
WARNING: 401 UNAUTHORIZED: Could not get favorite artists: Make sure you get your cookie file while logged in
INFO: Gathering favorite users
WARNING: 401 UNAUTHORIZED: Could not get favorite artists: Make sure you get your cookie file while logged in
DEBUG: Completed in 00:00:03
INFO: Completed

```

**Comment by AplhaSlayer1964** [comment]
When was the last time you updated your cookies? If you logout of your account it might reset the session token. Also Kemonos site just broke the other night so session tokens might need to be reset.

**Comment by Nerodacles** [comment]
> 

I just updated it, but let me do it again.

**Comment by Nerodacles** [comment]
Jup, thanx, login-logout did it!
