### ISSUE TITLE
PIL Module?

### ISSUE THREAD

**Issue by GithubGuest99** [AplhaSlayer1964/kemono-dl#5]
Installed python, pip install bs4, got cookie.txt, tried id 35774349
Got error about missing module PIL

```
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\Kemono-DL\kemono-dl.py", line 11, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Tried pip install PIL, got

```
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL
```

Not sure what I should do. (I tried installing pillow but that gave other errors so im guessing that wasnt the solution

**Comment by GithubGuest99** [comment]
python kemono-dl.py --ignore-errors --cookies "cookie.txt" --links blah.blah/blah/35774349

```
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\Kemono-DL\kemono-dl.py", line 342, in <module>
    main()
  File "C:\Users\USERDownloads\Kemono-DL\kemono-dl.py", line 325, in main
    if not extract_link(link.lstrip()):
  File "C:\Users\USER\Downloads\Kemono-DL\kemono-dl.py", line 305, in extract_link
    get_pfp_banner(user_id, service, username)
  File "C:\Users\USER\Downloads\Kemono-DL\kemono-dl.py", line 280, in get_pfp_banner
    image = Image.open(io.BytesIO(api_responce.content))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 3023, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002C17CF47DB0>
```

**Comment by AplhaSlayer1964** [comment]
update to the newest release and make sure you use the --ignore-errors flag because their sight has a lot of broken links and the program will stop on them otherwise.

**Comment by AplhaSlayer1964** [comment]
> Version: 2021.10.07.3 Service: Patreon User id: 35774349
> 
> I called this command before:
> 
> `python kemono-dl.py --ignore-errors --cookies "cookies.txt" --links blahblahblah/35774349`

Does that command not work for you? Are you getting that 403 error? I just ran the post from that user where 2.mp4 was from and it downloaded without a problem. Was 1.mp4 able to download? 
```
Downloading: icon
Downloading: banner
Downloading: 1.mp4
[==================================================] 37.7/37.7 MB, 8.8 Mbpss
Downloading: 2.mp4
[==================================================] 37.7/37.7 MB, 7.8 Mbpss
Downloading: 1Rev.mp4
[==================================================] 37.7/37.7 MB, 14.1 Mbpss
Downloading: 2Rev.mp4
[==================================================] 37.7/37.7 MB, 8.3 Mbpsss
Downloading: 2000000.png
[==================================================] 2.0/2.0 MB, 27.3 Mbps
Downloading: 1000000.png
[==================================================] 1.9/1.9 MB, 36.8 Mbps
Downloading: 2000000.png
[==================================================] 2.0/2.0 MB, 6.4 Mbps
Completed downloading post id: 40317269 user id: 35774349
Done!
```

**Comment by AplhaSlayer1964** [comment]
> Version: kemono-dl 2021.10.09 Service: Patreon User id: 35774349
> 
> I followed the steps below. Install BeautifulSoup with pip insatll bs4 Install requirements with pip install -r requirements.txt
> 
> I called this command:
> 
> `python kemono-dl.py --ignore-errors --cookies "cookies.txt" --links https://kemono.party/patreon/user/35774349`
> 
> then I got this error message
> 
> ```
> C:\Users\TEST\Desktop\kemono-dl>python kemono-dl.py --ignore-errors --cookies "cookies.txt" --links https://kemono.party/patreon/user/35774349
> Downloading: gorilka [35774349] icon
> Error downloading: https://kemono.party/icons/patreon/35774349
> 403 Client Error: Forbidden for url: https://kemono.party/icons/patreon/35774349
> Traceback (most recent call last):
>   File "C:\Users\TEST\Desktop\kemono-dl\kemono-dl.py", line 271, in get_pfp_banner
>     image = Image.open(os.path.join(folder_path, file_name))
>   File "C:\Users\TEST\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2968, in open
>     fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\K\\Desktop\\kemono-dl\\Downloads\\patreon\\gorilka [35774349]\\gorilka [35774349] icon'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\TEST\Desktop\kemono-dl\kemono-dl.py", line 334, in <module>
>     main()
>   File "C:\Users\TEST\Desktop\kemono-dl\kemono-dl.py", line 318, in main
>     if not extract_link(link.lstrip()):
>   File "C:\Users\TEST\Desktop\kemono-dl\kemono-dl.py", line 309, in extract_link
>     get_pfp_banner(info)
>   File "C:\Users\TEST\Desktop\kemono-dl\kemono-dl.py", line 275, in get_pfp_banner
>     os.remove(os.path.join(folder_path, file_name)) # site might return garbage data if no icon or banner is found
> FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\K\\Desktop\\kemono-dl\\Downloads\\patreon\\gorilka [35774349]\\gorilka [35774349] icon'
> ```
> 
> To test if I can download the file, I put in the same User id and tested it, but I am getting this error.

It's annoying because I don't get the 403 error so it's hard to find these bugs. The problem was I didn't have a check to see if the user icon or banner had actually downloaded before it gets manually assigned a file extension. If you update to the new release 2021.10.10 this should be fixed so it won't crash there on a 403 error.

**Comment by neuromememachine** [comment]
2021.10.10 is working perfectly. I don't know if it's appropriate to thank you here, but I just want to say that I really appreciate it. Thank you.
