### ISSUE TITLE
Date or post id in file name

### ISSUE THREAD

**Issue by anon567321** [AplhaSlayer1964/kemono-dl#57]
Hello!
Can you please add the date or post id to the beginning of the file name? I usually move all files to the same folder, and because almost all files have [1]_[hash] in the name, the resulting folder is chaotic.
Also, is it possible to create a small database so that the program remembers files already downloaded, even if they have been moved to a different folder?
There is a similar database in the Pixiv downloader - Nandaka/PixivUtil2
https://github.com/Nandaka/PixivUtil2/releases
Thank you!

**Comment by AplhaSlayer1964** [comment]
If you don't want the file names indexed use `--no-indexing` and using `--archive` logs all completed posts to not be redownloaded. Also I do not put the file hash in the file name that is the original name from the server. I am working on dynamic naming for files but adding it retroactively is gonna take time. If you wish to add the date and post id to each file in the mean time just modify the `main.py` file.
