### ISSUE TITLE
Save all embeds into one file

### ISSUE THREAD

**Issue by SakhJack** [AplhaSlayer1964/kemono-dl#59]
### Description
Nowadays animators usually distribute videos through 3rd party service (mega, google, gofile, etc)
Is it possible to output ***only*** embedded links and to a single file?

### Reason
Easy import into download manager (JDownloader, MegaBasterd, etc)

**Comment by AplhaSlayer1964** [comment]
If you mean just links in the post content then `--extract-links` links will grab all href links in the posts content. This may include stuff you may not want to download. I should probably add the ability to pass a regex pattern in the future.

**Comment by SakhJack** [comment]
just tried this and don't see new file with combined embed,

**Comment by AplhaSlayer1964** [comment]
can you send the service, user id, and post id so I can try

**Comment by SakhJack** [comment]
`patreon/user/681782`
it just seems to create `content_links.txt` within each subdirectory
what I meant is to combine all `embed.txt` from one `user` into single cumulative file, sorry if too confusing

**Comment by AplhaSlayer1964** [comment]
Ah at the moment then no the program can't do that. I will keep that in mind though. Currently working on making the folder structure dynamic so you can organize this how you want. After that I'll see about adding a flag to do this. For now if you are on windows this batch script seems to do what you want, don't know though haven't tested. [https://stackoverflow.com/questions/34145656/how-to-merge-text-files-with-the-same-name-from-all-subdirectories](https://stackoverflow.com/questions/34145656/how-to-merge-text-files-with-the-same-name-from-all-subdirectories)
