### ISSUE TITLE
Skip sorting/skip making individual folders for every post.

### ISSUE THREAD

**Issue by TechnoMasterBoy** [AplhaSlayer1964/kemono-dl#61]
### Description
Would love for there to be a way that when you set it to download stuff from users, it doesn't make every single post into individual folders.
It's kinda annoying having for example 100 folders containing just 1 image/video in each.
Like it's cool that this kemono-dl can index stuff by date and post ID, but I'd much prefer just having 1 giant folder with everything in it so I can much easier actually see my downloaded stuff.

### Service, User ID, Post ID
Only tried on this site/service combo, but I assume it applies to everything:
- Site: coomer.party
- Service: onlyfans
- User ID: Any user
- Post ID: Any post

### Additional comments
Great program or whatever it's called btw. Found out about it today and it's an absolute lifesaver. Beats having to open thousands of individual posts, saving everything manually lol.

**Comment by AplhaSlayer1964** [comment]
Please look at this [pre release](https://github.com/AplhaSlayer1964/kemono-dl/releases/tag/2022.02.21). Have not tested many users so there may be bugs.
