### ISSUE TITLE
ignore/retry error

### ISSUE THREAD

**Issue by afterdelight** [AplhaSlayer1964/kemono-dl#72]
### Description
I have many favorites user from several platforms
and when I get this error
----------
ERROR: Failed to get favorite artists from kemono.party
INFO: Completed
----------
the program stopped as complete

### Additional comments
add ignore error command or retry multiple times when the error occured .ty thx

**Comment by AplhaSlayer1964** [comment]
If it failed to get favorite artist that normally means something is wrong with your cookie file. Can you confirm the cookie file is correct?

**Comment by afterdelight** [comment]
its correct probably the program stopped because of connection error. Sometimes i got error and the program stopped, sometimes it got fetched and running

**Comment by afterdelight** [comment]
probably it just doesnt have function to handle time out exception and retry the download

**Comment by AplhaSlayer1964** [comment]
Unfortunately I have had no free time to really work on this downloader. Hopefully I will have some free time soon.

**Comment by afterdelight** [comment]
ok, no problem

**Comment by AplhaSlayer1964** [comment]
Will add be adding a retry to getting list of all creators. New release should be this weekend.

**Comment by afterdelight** [comment]
Cool. I'll wait
