### ISSUE TITLE
--cookies and --archive Feature Request

### ISSUE THREAD

**Issue by BlademasterQAQ** [AplhaSlayer1964/kemono-dl#78]
### --cookies
The `--cookies` options is set REQUIRED now. If user does not provide cookie, it is more convenient that program get **Netscape** cookie by `request` automatically.

### --archive
The `--archive` options do not support [template variables](https://github.com/AplhaSlayer1964/kemono-dl#output-template)
It does not make sense. Could it requests and parses `--links` first and then load the other options?

Thanks!

**Comment by AplhaSlayer1964** [comment]
> The `--cookies` options is set REQUIRED now. If user does not provide cookie, it is more convenient that program get **Netscape** cookie by `request` automatically.

The reason for the cookies is because kemono.party uses DDOS Guard so passing cookies is the only way around it.

> The `--archive` options do not support [template variables](https://github.com/AplhaSlayer1964/kemono-dl#output-template)
> It does not make sense. 

The template variables are not used in `--archive` because it just logs the service, user id, and post id not file path. It is just used to skip posts that have completed successfully. 

> Could it requests and parses `--links` first and then load the other options?

I don't understand the question?

**Comment by BlademasterQAQ** [comment]
> > The `--cookies` options is set REQUIRED now. If user does not provide cookie, it is more convenient that program get **Netscape** cookie by `request` automatically.
> 
> The reason for the cookies is because kemono.party uses DDOS Guard so passing cookies is the only way around it.
> 
> > The `--archive` options do not support [template variables](https://github.com/AplhaSlayer1964/kemono-dl#output-template)
> > It does not make sense.
> 
> The template variables are not used in `--archive` because it just logs the service, user id, and post id not file path. It is just used to skip posts that have completed successfully.
> 
> > Could it requests and parses `--links` first and then load the other options?
> 
> I don't understand the question?

Thanks for your reply!

The second question is, I want to save the skip info individually. 
Because different service and user info in a single `archive.txt`, I thought it is hard to manage.

Thanks:)
