### ISSUE TITLE
Add values for --kemono-favorite-users 

### ISSUE THREAD

**Issue by afterdelight** [AplhaSlayer1964/kemono-dl#79]
### Description
Add values for --kemono-favorite-users such as patreon, gumroad, fanbox, fantia and all (default)
'--kemono-favorite-users patreon' will download only favorited patreon creators.

The reason i requested this because I have a different output option for gumroad download. TY.

**Comment by AplhaSlayer1964** [comment]
Good idea I think I will add this.

**Comment by afterdelight** [comment]
Thanks!

**Comment by AplhaSlayer1964** [comment]
added to newest release
