### ISSUE TITLE
coomer.party cant download

### ISSUE THREAD

**Issue by afterdelight** [AplhaSlayer1964/kemono-dl#80]
### Description of bug
using latest version

looks like coomeer.party add a ddos attack check before opening the site

I got error below.

### How To Reproduce
Just start the download

### Error messages and tracebacks

```
**ERROR: Failed to get creator info from coomer.party
ERROR: Failed to find user for service:onlyfans user_id:misswarmjfree
INFO: Completed
```

**Comment by AplhaSlayer1964** [comment]
Can you post your command? I assume you passed cookies for coomer.party.

**Comment by AplhaSlayer1964** [comment]
Sometimes the creator api fails so in the next update I will have it retry incase that happens.

**Comment by afterdelight** [comment]
my command is:
kemono-dl.py --cookies onlyfans_cookies.txt --links https://coomer.party/onlyfans/user/misswarmjfree -o "/{site}/{service}/{username} [{user_id}]/[{published}] [{id}] [{index}] {name}.{ext}" --extract-links --save-banner --save-icon --skip-embed --yt-dlp --archive onlyfans_downloaded.txt
pause

**Comment by afterdelight** [comment]
its the same for no cookies

**Comment by afterdelight** [comment]
hmm suddenly it fixed it self. weird. now i can download flawlessly

**Comment by AplhaSlayer1964** [comment]
> hmm suddenly it fixed it self. weird. now i can download flawlessly

That's good to hear. I know both sites can be unreliable sometimes.
