### ISSUE TITLE
(question) DMs

### ISSUE THREAD

**Issue by afterdelight** [AplhaSlayer1964/kemono-dl#82]
### Additional comments
Does kemono-dl support DM download?

**Comment by AplhaSlayer1964** [comment]
Not currently. Can you send a user that has direct messages available to view.

**Comment by afterdelight** [comment]
here is one off the example:
https://kemono.party/patreon/user/1373963/dms

**Comment by AplhaSlayer1964** [comment]
Ok I will look into adding this. There isn't a api method to get the info so I will have to do normal web scraping. If you know any other users with dms post them here. It will be easier to make a more general scraper if I have access to more dm pages.

**Comment by afterdelight** [comment]
ok, ty for your hardwork

**Comment by AplhaSlayer1964** [comment]
Added in release [2022.04.24](https://github.com/AplhaSlayer1964/kemono-dl/releases/tag/2022.04.24)

**Comment by AplhaSlayer1964** [comment]
The dms download following the `--user-filename-pattern`
