### ISSUE TITLE
Several issues with 2022.04.22

### ISSUE THREAD

**Issue by sybarix** [AplhaSlayer1964/kemono-dl#84]
### Version
Version: 2022.04.22

### 1) --verbose doesn't seem to generate debug.log
```bash @echo off
py kemono-dl.py --cookies "kemono.party_cookies.txt,coomer.party_cookies.txt" --kemono-fav-users all --coomer-fav-users all --skip-filetypes PSD --inline --content --comments --extract-links --icon --banner --yt-dlp --dirname-pattern "Downloads\{username} [{user_id}]" --filename-pattern "({published}) {index} - {filename} [{id}].{ext}" --verbose
pause
```

### 2) single quote used in example on main post, but doesn't work with spaces. Double quotes needed.
```bash @echo off
py kemono-dl.py --cookies "kemono.party_cookies.txt,coomer.party_cookies.txt" --kemono-fav-users all --coomer-fav-users all --skip-filetypes PSD --inline --content --comments --extract-links --icon --banner --yt-dlp --dirname-pattern 'Downloads\{username} [{user_id}]' --filename-pattern '({published}) {index} - {filename} [{id}].{ext}' --verbose
pause
```

### Error messages and tracebacks
```python

usage: kemono-dl.py [-h] --cookies FILE [--links LINKS] [--from-file FILE] [--kemono-fav-users SERVICE]
                    [--coomer-fav-users SERVICE] [--kemono-fav-posts] [--coomer-fav-posts] [--inline] [--content]
                    [--comments] [--json] [--extract-links] [--icon] [--banner] [--yt-dlp] [--skip-attachments]
                    [--overwrite] [--dirname-pattern DIRNAME_PATTERN] [--filename-pattern FILENAME_PATTERN]
                    [--inline-filename-pattern INLINE_FILENAME_PATTERN]
                    [--content-filename-pattern CONTENT_FILENAME_PATTERN] [--date-strf-pattern DATE_STRF_PATTERN]
                    [--restrict-names] [--archive FILE] [--date YYYYMMDD] [--datebefore YYYYMMDD]
                    [--dateafter YYYYMMDD] [--user-updated-datebefore YYYYMMDD] [--user-updated-dateafter YYYYMMDD]
                    [--min-filesize SIZE] [--max-filesize SIZE] [--only-filetypes EXT] [--skip-filetypes EXT]
                    [--version] [--verbose] [--quiet] [--simulate] [--no-part-files] [--yt-dlp-args YT_DLP_ARGS]
                    [--post-timeout SEC] [--retry COUNT] [--ratelimit-sleep SEC] [--user-agent UA]
kemono-dl.py: error: unrecognized arguments: [{user_id}]' {index} - {filename} [{id}].{ext}'
Press any key to continue . . .

```

Fix: replace ' with " and it works

### 3) Can't change output path
```bash @echo off
 --dirname-pattern "D:\Storage\..."
```
expected result: output changes to "D:\Storage\..."
actual result: output changes to "D:\_\Storage\..."
fix: use symlinks for now i guess

### 4) Date command doesn't work as expected
command 1:
```bash @echo off
--date-strf-pattern %y%m%d
```
expected result: using {published} in filename results in 220423
actual result: using {published} in filename results in (md)

command 2:
```bash @echo off
--date-strf-pattern %Y%m%d
```
expected result: using {published} in filename results in 20220423
actual result: using {published} in filename results in ('md')

command 3:
```bash @echo off
--date-strf-pattern %y/%m/%d
```
expected result: using {published} in filename results in 22/04/23
actual result: using {published} in filename results in (m_d)

**Comment by AplhaSlayer1964** [comment]
> ### 1) --verbose doesn't seem to generate debug.log
> ```shell
> py kemono-dl.py --cookies "kemono.party_cookies.txt,coomer.party_cookies.txt" --kemono-fav-users all --coomer-fav-users all --skip-filetypes PSD --inline --content --comments --extract-links --icon --banner --yt-dlp --dirname-pattern "Downloads\{username} [{user_id}]" --filename-pattern "({published}) {index} - {filename} [{id}].{ext}" --verbose
> pause
> ```

I am aware of this. I still needed to redo the debug info so `--verbose` is kind of useless in this build.

> ### 2) single quote used in example on main post, but doesn't work with spaces. Double quotes needed.
> ```shell
> py kemono-dl.py --cookies "kemono.party_cookies.txt,coomer.party_cookies.txt" --kemono-fav-users all --coomer-fav-users all --skip-filetypes PSD --inline --content --comments --extract-links --icon --banner --yt-dlp --dirname-pattern 'Downloads\{username} [{user_id}]' --filename-pattern '({published}) {index} - {filename} [{id}].{ext}' --verbose
> pause
> ```

Oops kind of just copied them from the script. Forgot windows terminal doesn't like single quotes. 

> ### 3) Can't change output path
> ```shell
>  --dirname-pattern "D:\Storage\..."
> ```
> 
> expected result: output changes to "D:\Storage..." actual result: output changes to "D:_\Storage..." fix: use symlinks for now i guess

Yes it seems I forgot to re add the absolute path check so the `:` is getting turned into an `_`

> ### 4) Date command doesn't work as expected
> command 1:
> 
> ```shell
> --date-strf-pattern %y%m%d
> ```
> 
> expected result: using {published} in filename results in 220423 actual result: using {published} in filename results in (md)
> 
> command 2:
> 
> ```shell
> --date-strf-pattern %Y%m%d
> ```
> 
> expected result: using {published} in filename results in 20220423 actual result: using {published} in filename results in ('md')
> 
> command 3:
> 
> ```shell
> --date-strf-pattern %y/%m/%d
> ```
> 
> expected result: using {published} in filename results in 22/04/23 actual result: using {published} in filename results in (m_d)

You must be running it from a windows batch script so you must use %% to pass a literal %. That is a windows batch limitation not the scripts.

**Comment by sybarix** [comment]
>You must be running it from a windows batch script so you must use %% to pass a literal %. That is a windows batch limitation not the scripts.
Yup I'm using a batch script. Replacing % with %% makes it work as expected, thanks!

**Comment by AplhaSlayer1964** [comment]
For issue 3 I actually found why it is doing that weird `_`. I'll push an update in like 30 minutes.

**Comment by AplhaSlayer1964** [comment]
https://github.com/AplhaSlayer1964/kemono-dl/releases/tag/2022.04.23
