### ISSUE TITLE
Exlude file name

### ISSUE THREAD

**Issue by afterdelight** [AplhaSlayer1964/kemono-dl#89]
I want to exclude file downlaod which has a word PSD in the file name since i dont want to download huge PSD files. How to do that?

**Comment by afterdelight** [comment]
No its in the file name not the extension. I also want to skip file with kor(korean) worrd in it since i cant read koreans.

**Comment by AplhaSlayer1964** [comment]
Then I would use `--max-filesize SIZE` to not download large files (note: pdfs don't report file size so they won't be downloaded using this option). I don't plan on adding a exclusion by file name option. Feel free to make a pull request or clone the repo and add the feature yourself though. You could use some regex check for the string PSD and maybe some unicode check for the korean letters.

**Comment by afterdelight** [comment]
but they have english version which is the file size is similiar so i want to download english version while not downloading korean vesion.
well its okay i though there was a --filter-string or a --match-string option before

**Comment by AplhaSlayer1964** [comment]
>i though there was a --filter-string or a --match-string option before

nope but shouldn't be to hard for you to add.

**Comment by afterdelight** [comment]
what do you mean by that
