### ISSUE TITLE
I want to re-download only the posts that have an error during download. Is there a way?

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [AplhaSlayer1964/kemono-dl#9]
If an archive txt is generated even for a post with an error, it is recorded as being processed normally, and the file is missing because it is not downloaded again even if options such as -favorite-users are used.
A function that attempts to re-download the post with an error by marking it separately in the archive is required.

In addition, you need an option to add an index to attachments and posts when downloading. (Currently, there is no additional index to the file name when downloading, and there is a problem that the order is mixed when sorting the file name)

**Comment by AplhaSlayer1964** [comment]
can you give me an example? ie service, userid, postid
Kemono.party may change the names on their front end but the api should have the correct uploaded name.

**Comment by MagmaChipmunk** [comment]
I'll post those IDs and screenshots after I get home from work.🥲

**Comment by AplhaSlayer1964** [comment]
ok np
