### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by ninko76** [AplhaSlayer1964/kemono-dl#90]
![Annotation 2022-04-26 174421](https://user-images.githubusercontent.com/103625285/165416500-a83a3475-0171-4fdc-bea6-37a76c119913.png)
How would I resolve this issue?

**Comment by AplhaSlayer1964** [comment]
`pip install pillow` looks like it got removed from my requirements.txt somehow.

**Comment by afterdelight** [comment]
it sayas PIL lol
